name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    concurrency:
      group: 'install-dependencies'
      cancel-in-progress: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Poetry 1.8.5
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "Poetry installed at: $HOME/.local/bin/poetry"
        # Potwierdzenie wersji Poetry
        $HOME/.local/bin/poetry --version
        # Dodanie Poetry do ścieżki środowiska
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: ./example-app/.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Install project dependencies
      working-directory: ./example-app
      run: |
        poetry install --no-root
