name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    concurrency:
      group: "install-dependencies-${{ github.ref }}"
      cancel-in-progress: true  # Zapewnia, że tylko jedno zadanie w danym czasie będzie aktywne

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Add Poetry to PATH
        run: echo "/home/student/.local/bin" >> $GITHUB_PATH  # Dodajemy Poetry do PATH

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -  # Instalacja Poetry
          echo "/home/student/.local/bin" >> $GITHUB_PATH  # Upewniamy się, że jest dodane do PATH

      - name: Install project dependencies
        run: poetry install --no-root  # Instalacja zależności projektu

  linting:
    runs-on: ubuntu-latest
    concurrency:
      group: "linting-${{ github.ref }}"
      cancel-in-progress: true  # Zapewnia, że tylko jedno zadanie w danym czasie będzie aktywne
    needs: install-dependencies  # To zadanie zależy od zadania instalacji zależności

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Add Poetry to PATH
        run: echo "/home/student/.local/bin" >> $GITHUB_PATH  # Dodajemy Poetry do PATH

      - name: Run Linter
        run: poetry run task lint  # Uruchomienie lintera

      - name: Run Formatter
        run: poetry run task formatter  # Uruchomienie formatera

      - name: Run Security Check
        run: poetry run task security  # Uruchomienie testów bezpieczeństwa

  unit-tests:
    runs-on: ubuntu-latest
    concurrency:
      group: "unit-tests-${{ github.ref }}"
      cancel-in-progress: true  # Zapewnia, że tylko jedno zadanie w danym czasie będzie aktywne
    needs: install-dependencies  # To zadanie zależy od zadania instalacji zależności

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Add Poetry to PATH
        run: echo "/home/student/.local/bin" >> $GITHUB_PATH  # Dodajemy Poetry do PATH

      - name: Run Unit Tests
        run: poetry run task test  # Uruchomienie testów jednostkowych

  cache:
    runs-on: ubuntu-latest
    needs: install-dependencies  # To zadanie zależy od zadania instalacji zależności

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache Poetry Dependencies
        uses: actions/cache@v3
        with:
          path: /home/runner/work/<your-repository>/<your-repository>/.venv  # Zastąp ścieżkę odpowiednio do Twojego repo
          key: ${{ runner.os }}-poetry-dependencies-${{ hashFiles('**/poetry.lock') }}  # Generowanie klucza cache na podstawie pliku poetry.lock
          restore-keys: |
            ${{ runner.os }}-poetry-dependencies-

