name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    concurrency:
      group: 'install-dependencies'
      cancel-in-progress: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Poetry and add it to PATH
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "Poetry installed at: $HOME/.local/bin/poetry"
        echo "Adding Poetry to PATH"
        export PATH="$HOME/.local/bin:$PATH"
        echo "Poetry installed at: $HOME/.local/bin"
        poetry --version  # Sprawdzamy, czy Poetry jest zainstalowane
        # Dodajemy PATH do środowiska, aby było dostępne w dalszych krokach
        echo "PATH=$PATH" >> $GITHUB_ENV

    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: ./example-app/.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Install project dependencies
      working-directory: ./example-app
      run: poetry install --no-root

  static_analysis:
    runs-on: ubuntu-latest
    concurrency:
      group: 'static-analysis'
      cancel-in-progress: true
    needs: install_dependencies

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Run linting
      working-directory: ./example-app
      run: |
        poetry run task lint

    - name: Run formatter
      working-directory: ./example-app
      run: |
        poetry run task formatter

    - name: Run security checks
      working-directory: ./example-app
      run: |
        poetry run task security

  unit_tests:
    runs-on: ubuntu-latest
    concurrency:
      group: 'unit-tests'
      cancel-in-progress: true
    needs: install_dependencies

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Run unit tests
      working-directory: ./example-app
      run: |
        poetry run task test
