name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    concurrency:
      group: "install-dependencies-${{ github.ref }}"
      cancel-in-progress: true

    steps:
      # Krok 1: Checkout kodu z repozytorium
      - name: Check out code
        uses: actions/checkout@v3

      # Krok 2: Instalacja Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH  # Dodajemy Poetry do ścieżki

      # Krok 3: Sprawdzenie instalacji Poetry
      - name: Check Poetry Installation
        run: |
          which poetry  # Sprawdzi, gdzie jest zainstalowane poetry
          poetry --version  # Wyświetli wersję zainstalowanego poetry

      # Krok 4: Cache Poetry Dependencies
      - name: Cache Poetry Dependencies
        uses: actions/cache@v3
        with:
          path: /home/runner/work/iac-labs/iac-labs/example-app/.venv
          key: ${{ runner.os }}-poetry-dependencies-${{ hashFiles('example-app/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-dependencies-

      # Krok 5: Przejście do katalogu example-app
      - name: Change to example-app directory
        run: cd example-app

      # Krok 6: Instalacja zależności projektu
      - name: Install Project Dependencies
        run: |
          echo "Checking if poetry is installed..."
          which poetry  # Sprawdzenie, czy poetry jest w systemie
          poetry --version  # Sprawdzenie wersji poetry
          cd example-app  # Przechodzimy do katalogu example-app
          $HOME/.local/bin/poetry install --no-root  # Użycie pełnej ścieżki do poetry

      # Krok 7: Uruchomienie testów jednostkowych
      - name: Run Unit Tests
        run: |
          cd example-app  # Upewniamy się, że jesteśmy w katalogu example-app
          $HOME/.local/bin/poetry run task test  # Uruchomienie testów jednostkowych

      # Krok 8: Linter, Formatter, Security
      - name: Run Static Code Analysis (Linter, Formatter, Security)
        run: |
          cd example-app  # Upewniamy się, że jesteśmy w katalogu example-app
          $HOME/.local/bin/poetry run task lint  # Uruchomienie testów statycznych kodu
          $HOME/.local/bin/poetry run task formatter  # Uruchomienie formatera kodu
          $HOME/.local/bin/poetry run task security  # Uruchomienie testów bezpieczeństwa
