name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.2.2

    - name: Install dependencies
      run: poetry install --no-root

    - name: Run tests
      run: poetry run task test

    - name: Run linting
      run: poetry run task lint

    - name: Run security checks
      run: poetry run task security
